# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fbb00d2d09683800ef16b83bce3969b02b64d4148f75d4de75106ae613b0bb0507b144e0c62f0a3088fad7dc41f1e9e1066c7f4a266a396b9a9d0e6fcff8c89

test:
  secret_key_base: a9d7ef8250b95d687a7c085f9ad48c8654fd250a3f932e91f9498df821361824fde1390a2845619e83de305ef190b5cefee1b93858c9142fc8d761220b076e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
